import { Router } from 'express';
import analyticsRoutes from './analyticsRoutes.js';
import authRoutes from './authRoutes.js';
import bookingRoutes from './bookingRoutes.js';
import messageRoutes from './messageRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import propertyRoutes from './propertyRoutes.js';
import supportTicketRoutes from './supportTicketRoutes.js';
import userRoutes from './userRoutes.js';

const router = Router();
router.use('/analytics', analyticsRoutes);
router.use('/auth', authRoutes);
router.use('/bookings', bookingRoutes);
router.use('/messages', messageRoutes);
router.use('/notifications', notificationRoutes);
router.use('/properties', propertyRoutes);
router.use('/support-tickets', supportTicketRoutes);
router.use('/users', userRoutes);
export default router;
